services:
- type: web
  name: amm-controller
  env: python
  plan: free
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn amm_controller.wsgi --workers 1 --log-file -"
  preDeployCommand: "python manage.py migrate"
